### ISSUE TITLE
self::$grav is undefined

### ISSUE THREAD

**Issue by loganfreeman** [kalebheitzman/grav-plugin-datetools#2]
$this->config = self::$grav['config'];

**Comment by Vivalldi** [comment]
@loganfreeman I also have this issue. It seems to appear only in production environments for me. the plugin works fine in localhost development though in production it fails

@kalebheitzman I would take a look at how other plugins call grav and it's config

**Comment by kalebheitzman** [comment]
@Vivalldi are there any plugins you would recommend specifically that I look at? Thanks.

**Comment by Vivalldi** [comment]
So the grav object is a protected attribute of the plugin class. So in the [login plugin](https://github.com/getgrav/grav-plugin-login/blob/develop/login.php#L71) it calls `$this->grav['config']` which calls the config container

**Comment by daz3dpr0z** [comment]
I have just installed datetools as it was required by the event plugin. Then on loading my site after the install it appears i also have a similar issue

`Access to undeclared static property: Grav\Plugin\DateTools::$grav`

It seems to throw the error at the following point in the datetools.php

`$this->config = self::$grav['config'];`

I can set `enabled: false` in the .yaml file and my site works again .

Perhaps i should have opened another thread for this issue. if so let me know and i will create a new one.

regards jimmy

**Comment by kalebheitzman** [comment]
This is fixed with v1.0.3. Pushing the release today.
