### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by ghost** [kalebheitzman/grav-plugin-datetools#3]
New GRAV Beta + DateTools = See Attachment

I'm looking to use the new Events plugin for GRAV. I installed the required Datetools but got this error under the latest version of GRAV Beta. I have not made any adjustments at this point, but had to disable the plugin in order to continue developing the rest of the site.

Suggestions?

Brian U.

![capture](https://cloud.githubusercontent.com/assets/5008228/14965462/39d80b36-1073-11e6-8bcc-58219e53b3d1.PNG)

**Comment by kalebheitzman** [comment]
Related to Issue #2
