### ISSUE TITLE
Pages directory of your demo page somewhere available

### ISSUE THREAD

**Issue by janklostermann** [kalebheitzman/grav-plugin-datetools#4]
It would be really cool to be able to have a look into the backyard of your demo site (as git repo, or dropbox/owncloud/whatoever file server).

Somehow I do not get your cool plugin running. It does not recognize the events that I added to the frontmatter of the pages of the grav-skeleton-blog-site. Therefore it would be cool to have something to play with that already works, or see how the working stuff is built behind the scenes...

Thanks for considering.
Jan

**Comment by kalebheitzman** [comment]
@janklostermann Check the actual [Events plugin](https://github.com/kalebheitzman/grav-plugin-events) documentation. This is the DateTools plugin. I've linked to some content there :)

**Comment by janklostermann** [comment]
Sorry for putting into here and not to the events plugin. (If you want we can shift the discussion there, too.)
But anyhow I could not find some markdown files creating the output - sample content that should work out of the box following the install instructions, to reduce potential error sources for debugging. 
Or is there a skeleton to play with that includes a calender/the events plugin, that you could reference?
