### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by timoransky** [kalebheitzman/grav-plugin-datetools#5]
Hello, when i enable this plugin i get this error

> Whoops\Exception\ErrorException thrown with message "Call to a member function get() on a non-object"
> Stacktrace:
> # 0 Whoops\Exception\ErrorException in /home/2011/11timoransky/www/grav/user/plugins/datetools/classes/datetools.php:65

When i disable it, everything works fine. Can you help me?

**Comment by paulcmal** [comment]
I'm having the same issue with Grav v1.1.0-rc.2.
No problem on the stable release though. Plugin needs updating for the next release :)

**Comment by nsteinmetz** [comment]
Same here with 1.1rc3 - may have to downgrade to 1.0.x then ;-)

**Comment by OleVik** [comment]
Are there any plans to resolve this? The plugin has seemingly been incompatible with Grav for a while now.

**Comment by kalebheitzman** [comment]
Hey guys, I'm going to push a fix this week. Maybe even today.

**Comment by kalebheitzman** [comment]
This has been fixed with [Release 1.0.4](https://github.com/kalebheitzman/grav-plugin-datetools/releases/tag/1.0.4)
