### ISSUE TITLE
Update version in blueprint

### ISSUE THREAD

**Issue by flaviocopes** [kalebheitzman/grav-plugin-datetools#6]
Lists 1.0.1, otherwise it's not listed as update in the GPM 👍

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav/issues/925#issuecomment-230343281

**Comment by paulcmal** [comment]
@flaviocopes The blueprint [was updated](https://github.com/kalebheitzman/grav-plugin-datetools/commit/1123a8dbbb549a6b726c44620cb0f96636731d79) but somehow v1.0.1 is still the one listed in the [plugins](https://getgrav.org/downloads/plugins).

I just tried to `bin/gpm install events` on 1.1 RC3 and I got datetools v1.0.1 (version before 1.1 compatibility).

**Comment by paulcmal** [comment]
@rhukster found out why: https://github.com/getgrav/grav/issues/925#issuecomment-231838590
It appears you just have to remove old tags starting with 'v' to let GPM pickup your latest commit :)

**Comment by kalebheitzman** [comment]
I've deleted the old tags that start with "v" and will be pushing an update tonight.
